### ISSUE TITLE
Mate bug

### ISSUE THREAD

**Issue by BadPizza23** [Thlumyn/clangen#148]
The mates are broken? Same mates for lots of cats, and they never have kits?

**Comment by JustAGur1** [comment]
not only that,sometimes they don't even appear as mates,or have 2 mates

**Comment by shrimpsicle** [comment]
Hi, specifics of this issue for whoever gets to it is that say Cat 1 picks Cat 2 as a mate, Cat 2's page will not show as having any mate and then random cats from the Clan can choose Cat 2 as a mate as well.

**Comment by BadPizza23** [comment]
Yeah, It's super strange, makes it hard to play :(

**Comment by BadPizza23** [comment]
one more thing, I turn off self mating, and it still self mates..? thanks :)

**Comment by BadPizza23** [comment]
So, the mating is fixed! But the other problem, is that when you turn off Self-Mating, Cats still mate each other without asking.

**Comment by apercival** [comment]
Mild update: Still experiencing a bug here, though potentially slightly different than described. Adding a mate makes those two cats mates, but cats not associated with the relationship can take one of those cats as a mate, as well.

**Comment by Ryos00** [comment]
This bug has been fixed
